apiVersion: v2
name: api-service
description: REST API microservice with HPA, Ingress, and NetworkPolicy
type: application
version: 0.5.0
appVersion: "1.4.2"
maintainers:
  - name: Abad Naseer
    email: abad.naseerfast@gmail.com
keywords:
  - api
  - microservice
  - kubernetes
